- name: Install dependencies
  package:
    name:
      - python3
      - python3-pip
    state: present

- name: Install prometheus-client
  pip:
    name: prometheus-client
    state: present

- name: Copy application
  copy:
    src: metrics_app.py
    dest: /opt/metrics_app.py
    mode: 0755

- name: Create systemd service
  template:
    src: metrics.service.j2
    dest: /etc/systemd/system/metrics.service
  notify: restart metrics

- name: Start and enable service
  systemd:
    name: metrics
    state: started
    enabled: yes
    
- meta: flush_handlers

- name: Ensure Docker is installed
  package:
    name: docker
    state: present
  when: deployment_method == "docker"

- name: Build Docker image
  docker_image:
    name: metrics-app
    source: build
    build:
      path: "{{ role_path }}/files"
    state: present
  when: deployment_method == "docker"

- name: Run Docker container
  docker_container:
    name: metrics-app
    image: metrics-app
    ports: "8080:8080"
    state: started
  when: deployment_method == "docker"